base/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    # Main
    path('', main, name='main'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login_user'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('genre/<str:pk>', BookGenreView.as_view(), name='book_genre'),
    
    #Profile 
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>', ProfileEditView.as_view(), name='profile_edit'),
    path('profile/book-add/', UserBookAddView.as_view(), name='user_book_add'),
    path('profile/blog-add/', UserBlogAddView.as_view(), name='user_blog_add'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meloman/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('admin_panel.urls')),
]

base/models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(max_length=1)
    is_active = models.BooleanField(default=False)
    
    # additionally
    image = models.ImageField(upload_to='users/', null=True)
    email = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=50, null=True)
    fullname = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.username


class Book(models.Model):
    title = models.CharField(max_length=70, help_text="The title of the book.")
    image = models.ImageField(upload_to='images/')
    rating = models.IntegerField(help_text="The the reviewer has given.")
    author = models.CharField(max_length=70, help_text="The name of Author")
    price = models.CharField(max_length=10, help_text="Price of book")
    is_published = models.BooleanField(default=False)
    genre = models.CharField(null=True,max_length=70, help_text="The genre of the book.")
    description = models.TextField(help_text="A detailed description of the book.", null=True)
    pages = models.IntegerField(help_text="The number of pages in the book.", null=True)
    publisher = models.CharField(max_length=100, help_text="The publisher of the book.", null=True)
    publish_date = models.DateField(help_text="The publication date of the book.", null=True)
    language = models.CharField(max_length=50, help_text="The language of the book.", null=True)
    book_type = models.CharField(max_length=50, help_text="The type of the book.", null=True)
   
    def __str__(self):
        return self.title

class Blog(models.Model):
    title = models.CharField(max_length=150, help_text="The title of the blog")
    date = models.DateField(auto_now_add=True)
    publisher = models.CharField(max_length=100, help_text="The publisher of the blog", null=True)
    description = models.TextField(help_text="A description of the blog", null=True)
    image = models.ImageField(upload_to='blogs/')

base/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'age', 'gender']

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise ValidationError(_('Password must be at least 8 characters long.'))
        if not any(char.isdigit() for char in password):
            raise ValidationError(_('Password must contain at least one digit.'))
        if not any(char.isupper() for char in password):
            raise ValidationError(_('Password must contain at least one uppercase letter.'))
        if not any(char.islower() for char in password):
            raise ValidationError(_('Password must contain at least one lowercase letter.'))
        return password

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        age = cleaned_data.get('age')
        gender = cleaned_data.get('gender')

        if password and confirm_password and password != confirm_password:
            raise ValidationError(_("Passwords don't match."))
        
        if User.objects.filter(username=username).exists():
            raise ValidationError(_('This username is already taken.'))
        
        
        
        
class AddNewBlog(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'publisher', 'description', 'image']
        
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'autocomplete': 'off'}),
            'publisher': forms.TextInput(attrs={'placeholder': 'Your Name', 'autocomplete': 'off'}),
            'description': forms.Textarea(attrs={'placeholder': 'description', 'min': '1', 'autocomplete': 'off'}),
        }



class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=50, help_text="Enter your desired username", widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'autocomplete': 'off'}))
    password = forms.CharField(max_length=50, help_text="Enter a strong password", widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', 'autocomplete': 'off'}))
    confirm_password = forms.CharField(max_length=50, help_text="Confirm your password",
                                       widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    age = forms.IntegerField(help_text="Enter your age", widget=forms.NumberInput(
        attrs={'placeholder': 'Enter age', 'min': '1'}))
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female'), ('O', 'Other')]
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES, widget=forms.RadioSelect, help_text="Select your gender")

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from hashlib import sha256
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.db.models import Count
from django.db.models import Q
from django.views import View
from django.views.generic.edit import CreateView
from .models import *
from .utils import validate_form_data
from admin_panel.models import AddNewBook
import os
import sys
from .forms import * 


#? REGISTER USER
class RegisterView(View):
    def get(self, request):
        response = render(request, 'base/register.html')
        response['Cache-Control'] = 'no-cache'
        return response
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        password_hash = sha256(password.encode()).hexdigest()
        age = request.POST.get('age')
        gender = request.POST.get('gender')

        # Validate form data
        errors = validate_form_data(username, password, confirm_password, age, gender)
        if errors:
            error_message = list(errors.values())[-1]
            messages.add_message(request, messages.ERROR, error_message)
            return redirect('register')

        obj = User()
        obj.username = username
        obj.password = password_hash
        obj.age = age
        obj.gender = gender
        obj.save()
        messages.success(request, 'Registration successful!')
        return redirect('login_user')

# ? LOGIN USER
class LoginUserView(View):
    def get(self, request):
        context = {}
        return render(request, 'base/login.html', context)
    
    def post(self, request):
        context = {}
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            password_hash = sha256(password.encode()).hexdigest()
            data = User.objects.get(username=username, password=password_hash)
            
            if data is not None:
                request.session['data_id'] = data.id
                return redirect(reverse('main'))
            
        except Exception as e:
            context['error'] = "Invalid username or password"

        return render(request, 'base/login.html', context)


#*----------Profile User----------

# ? PROFILE
class ProfileView(View):
    def get(self, request, pk):
        user = get_object_or_404(User, id=pk)
        return render(request, 'base/profile.html', {'user': user})
    
# ? Edit user info
class ProfileEditView(View):
    def get(self, request, pk):
        user = get_object_or_404(User, id=pk)
        return render(request, 'base/profile_edit.html', {'user': user})

    def post(self, request, pk):
        user = get_object_or_404(User, id=pk)
        user.username = request.POST.get('username')
        user.age = request.POST.get('age')
        user.email = request.POST.get('email')
        user.phone = request.POST.get('phone')
        user.fullname = request.POST.get('fullname')
        
        hash_password = sha256((request.POST.get('password')).encode()).hexdigest() 
        user.password = hash_password
        
        image_file = request.FILES.get('image')
        if image_file:
            if user.image:
                os.remove(os.path.join(settings.MEDIA_ROOT, str(user.image)))
            user.image = image_file
            
        user.save()
        return redirect('profile', pk=pk)
    
# ? User Add Book
class UserBookAddView(CreateView):
    model = Book
    form_class = AddNewBook
    template_name = 'base/user_add_book.html'
    success_url = reverse_lazy('main')

    def form_valid(self, form):
        form.instance.is_published = False
        return super().form_valid(form)
    
# # ? User Add Book
class UserBlogAddView(CreateView):
    model = Blog
    form_class = AddNewBlog
    template_name = 'base/user_add_blog.html'
    success_url = reverse_lazy('main')

    def form_valid(self, form):
        return super().form_valid(form)
    
#? Logout User
class LogoutView(View):
    def get(self, request):
        request.session.flush()
        return redirect('login_user')

    
#*----------Views----------

#? Book genres
class BookGenreView(View):
    def get(self, request, pk):
        context = {}
        books = Book.objects.filter(genre__icontains=pk)
        context['books'] = books
        context['genre_name'] = pk
        return render(request, 'base/genres.html', context)
    
#? Blog
class BlogView(View):
    def get(self, request):
        blogs = Blog.objects.all()
        return render(request, 'base/blog.html', {'blogs' : blogs})

#? Contact
class ContactView(View):
    def get(self, request):
        return render(request, 'base/contact.html')
        
#? MAIN   
def main(request):
    context = {}
    data_id = request.session.get('data_id')
    if data_id is not None:
        data = User.objects.get(id=data_id)
        context['data'] = data

    #all books
    books = Book.objects.filter(is_published=True)
    context['books'] = books
    
    #best author books
    best_author = Book.objects.filter(author='Khaled Hosseini')
    context['best_author'] = best_author

    #best author books
    upcomings = Book.objects.all().order_by('-id')[:4:1]
    context['upcomings'] = upcomings 
      
    #genre list
    genre_list = sorted(Book.objects.values('genre').annotate(num_books=Count('id')), key=lambda x: x['genre'])
    context['genre_list'] = genre_list
        
    search_input = request.GET.get('search') or ''
    search_results = Book.objects.none()
    last_viewed = Book.objects.none()
    
    # seach-area;
    if search_input:
        search_results = Book.objects.filter(title__icontains=search_input)
        context['books'] = search_results
        context['flag'] = 'Flag'
        
        search_history = request.session.get('search_history', [])
        if search_history:
            last_viewed = Book.objects.filter(title__icontains=search_history[-1])
            
        search_history.append(search_input)
        search_history = search_history[-5:]
        request.session['search_history'] = search_history
    
    context['last_viewed'] = last_viewed

    return render(request, 'base/main.html', context)

base/templates/base/blog.html
{% extends 'base/main.html' %}
{% block content %}
{% load static %}

<!-- header  -->
<header class="container mt-3">
    <div class="text-center">
        <a href="/" class="text-black">
            <h1 class="fs-1 fw-medium">Book<span class="text-danger">Wise</span></h1>
        </a>
    </div>
</header>

{% include 'base/includes/navbar.html' %}

<!-- banner blog  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'base/images/blog-page.png' %}" class="d-block w-100" alt="...">
        </div>
    </div>
</div>


<!-- section quotes  -->
<section class="quotes mb-5">
    <div class="container">
        <div class="text-center mt-5">
            <h2 class="fs-3 fw-medium">Quotes of the day:</h2>
            <q class="fst-italic d-block my-4">
                Just one small positive thought in the morning can change your whole day.
            </q>
            <button class="btn btn-danger">Change Quote</button>
        </div>
    </div>
</section>

<!-- all blogs  -->
<section class="all-blogs">
    <div class="container">
        <div class="row">
            <!-- left side  articles-->
            <div class="col-md-9 col-sm-12" id="articles">
                {% for blog in blogs %}

                <article class="mt-4">
                    <img src="{{blog.image.url}}" class="rounded-3 w-100" alt="">
                    <div class="d-flex gap-5 mt-3">
                        <h5><i class="fa fa-user" aria-hidden="true"></i> {{blog.publisher}}</h5>
                        <h5><i class="fa fa-calendar" aria-hidden="true"> {{blog.date}}</i></h5>
                    </div>
                    <h2 class="mt-3 fs-4 fw-bold">{{blog.title}}</h2>
                    <p>{{blog.description}}</p>
                </article>
                <hr>

                {% endfor %}
            </div>
            <!-- right side  -->
            <div class="col-md-3 col-sm-12">
                <h2 class="text-danger fs-5 fw-medium">Recent Posts</h2>
                <div class="d-flex flex-column rounded-3 border p-4 gap-3" id="recent-blogs">
                    {% for blog in blogs %}

                    <div class="info d-flex align-items-center gap-3">
                        <img src="{{blog.image.url}}" alt="${blog.title}">
                        <div class="d-flex flex-column">
                            <h5> <i class="fa fa-calendar" aria-hidden="true"></i> {{blog.date}}</h5>
                            <h2 class="fw-medium">{{blog.title}}</h2>
                        </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

base/templates/base/contact.html
{% extends 'base/main.html' %}
{% block content %}
{% load static %}



<!-- header  -->
<header class="container mt-3">
    <div class="text-center">
        <a href="/" class="text-black">
            <h1 class="fs-1 fw-medium">Book<span class="text-danger">Wise</span></h1>
        </a>
    </div>
</header>

{% include 'base/includes/navbar.html' %}


<!-- banner blog  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'base/images/contact-page.png' %}" class="d-block w-100" alt="...">
        </div>
    </div>
</div>


<!-- section contact us  -->
<section class="contact-us mt-5">
    <div class="container">
        <div class="d-flex justify-content-between flex-wrap">
            <iframe class="rounded-3"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d46533.244026375156!2d76.82251685820309!3d43.2026145!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3883689433766f49%3A0x66f7eb946908e6fa!2z0JzQldCb0J7QnNCQ0J0tTUFSV0lOINCi0KDQpiDCq01FR0EgQWxtYS1BdGHCuw!5e0!3m2!1sru!2skz!4v1671367911449!5m2!1sru!2skz"
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade">
            </iframe>
            <div class="forms d-flex flex-column align-items-start gap-3 mt-2">
                <h2 class="fs-2 fw-medium">We Would Love To Hear From You.</h2>
                <p>Your email address will not be published.</p>
                <input type="text" placeholder="Name" id="name" class="form-control rounded-4 p-2" autocomplete="off">
                <input type="text" placeholder="Subject" id="subject" class="form-control rounded-4 p-2"
                    autocomplete="off">
                <textarea placeholder="Message" class="form-control rounded-4" rows="6"></textarea>
                <div class="error hide text-danger">Ooops, Something goes wrong!</div>
                <button class="btn btn-danger" id="btn">Submit</button>
            </div>
        </div>
    </div>
</section>

<script async src="{% static 'base/js/sendEmail.js' %}"></script>
{% endblock content %}

base/templates/base/genres.html
{% extends 'base/main.html' %}
{% block content %}
{% load static %}

<!-- header  -->
<header class="container mt-3">
    <div class="text-center">
        <a href="/" class="text-black">
            <h1 class="fs-1 fw-medium">Book<span class="text-danger">Wise</span></h1>
        </a>
    </div>
</header>

{% include 'base/includes/navbar.html' %}

<!-- banner blog  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'base/images/genre-page.png' %}" class="d-block w-100" alt="...">
        </div>
    </div>
</div>

<h1 class="text-center text-uppercase mt-5 fs-4">{{genre_name}}</h1>
<!-- section cards boooks  -->
<section class="card-books">
    <div class="content d-flex flex-wrap justify-content-center" id="shop-books">
        {% for book in books %}

        <div class="d-flex gap-1 flex-column">
            <img src="{{book.image.url}}" alt="book">
            <div class="flex flex-column  content-info">
                <h4 class="fw-medium mt-2 mb-0">{{book.title}}</h4>

                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fa-solid fa-star-half-stroke"></i>
                    <i class="far fa-star"></i>
                    <span>{{book.rating}}</span>
                </div>

                <p>{{book.author}}</p>
                <div class="price">${{book.price}}</div>
            </div>
        </div>

        {% endfor %}

    </div>
</section>

{% endblock content %}

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}
{% load static %}

<!-- header  -->
<header class="container mt-3">
    <div class="text-center">
        <a href="/" class="text-black">
            <h1 class="fs-1 fw-medium">Book<span class="text-danger">Wise</span></h1>
        </a>
    </div>
</header>

{% include 'base/includes/navbar.html' %}

<!-- banner blog  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'base/images/account-page.png' %}" class="d-block w-100" alt="...">
        </div>
    </div>
</div>


<form method="POST" class="w-50 bg-danger-subtle p-5 d-flex flex-column align-items-center m-auto mt-5 gap-3 rounded-4">
    <h3 class="fs-2 fw-medium">Login</h3>
    {% csrf_token %}

    <input type="text" class="form-control p-2" name="username" placeholder="Username" id="username">
    <input type="password" class="form-control p-2" name="password" placeholder="Password" id="password">
    <button class="btn btn-danger px-5">Sign In</button>
    <hr>
    {% if error %}
    <p style="color: #f38282; font-size: .6em; margin-top: 10px;">{{ error }}</p>
    {% endif %}

    <p class="text-center">Don't have an account? <br> <a href="{% url 'register' %}">Register here</a></p>
</form>

{% endblock content %}

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}
{% load static %}

<!-- header  -->
<header class="container mt-3">
    <div class="text-center">
        <a href="/" class="text-black">
            <h1 class="fs-1 fw-medium">Book<span class="text-danger">Wise</span></h1>
        </a>
    </div>
</header>

{% include 'base/includes/navbar.html' %}

<!-- banner blog  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'base/images/account-page.png' %}" class="d-block w-100" alt="...">
        </div>
    </div>
</div>

<form method="POST" class="w-50 bg-danger-subtle p-5 d-flex flex-column align-items-center m-auto mt-5 gap-3 rounded-4">
    <h3 class="fs-2 fw-medium">Registration</h3>
    {% csrf_token %}

    <input type="text" class="form-control p-2" name="username" placeholder="Username" autocomplete="off"
        id="id_username">
    <input type="password" class="form-control p-2" name="password" placeholder="Password" autocomplete="off"
        id="id_password">
    <input type="password" class="form-control p-2" name="confirm_password" placeholder="Confirm Password"
        id="id_confirm_password">
    <input type="number" class="form-control p-2" name="age" placeholder="Enter age" min="1" id="id_age">

    <div id="gender" class="d-flex gap-3">
        <p>Gender: </p>
        <div id="id_gender" class="d-flex gap-3">
            <div>
                <label for="id_gender_0"><input type="radio" name="gender" value="M" id="id_gender_0">
                    Male
                </label>
            </div>
            <div>
                <label for="id_gender_1"><input type="radio" name="gender" value="F" id="id_gender_1">
                    Female
                </label>
            </div>
            <div>
                <label for="id_gender_2"><input type="radio" name="gender" value="O" id="id_gender_2">
                    Other
                </label>
            </div>
        </div>
    </div>

    {% if messages|length %}
    {% for message in messages %}
    <p style="color: #f38282; font-size: .6em; margin-top: 10px;">{{message}}</p>
    {% endfor %}
    {% endif %}

    <button class="btn btn-danger px-5" style="margin-top: 15px;">Register</button>
    <p class="text-center">Already have an account? <br> <a href="{% url 'login_user' %}">Login</a></p>
</form>

{% endblock content %}

base/templates/base/user_add_blog.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://simg.marwin.kz/media/favicon/stores/1/favicon.ico" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet" />
    <title>BookWise</title>
    <style>
        body {
            background-color: #fafafa;
        }

        form {
            max-width: 500px;
            margin: auto;
            margin-top: 50px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        textarea {
            display: block;
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
            margin-top: 5px;
        }

        textarea {
            resize: none;
        }

        input[type="submit"],
        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #008CBA;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            /* margin-top: 15px; */
        }

        input[type="submit"]:hover,
        .btn:hover {
            background-color: #006B9F;
            color: #fff;
        }

        .btn-primary {
            background-color: #ccc;
            color: #000;
        }

        .btn-primary:hover {
            background-color: #aaa;
        }

        p {
            margin: 0;
            margin-top: 30px;
            color: #f57373;
        }
    </style>

</head>

<body>
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <h2>Add new Blog 📑</h2>
            <div class="form-group"> {{ form.publisher }}</div>

            <div class="form-group"> {{ form.title }} </div>

            <div class="form-group"> {{ form.description }} </div>

            <div class="form-group">{{ form.image }}</div>

            <input class="btn" type="submit" value="Add Blog" style="margin-top: 15px;">
            <p class="text-center">Don't wanna add a new blog? <a href="/" class="btn btn-primary">Cancel</a></p>
        </form>
    </div>
</body>

</html>

base/templates/base/user_add_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://simg.marwin.kz/media/favicon/stores/1/favicon.ico" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet" />
    <title>BookWise</title>

    <style>
        body {
            background-color: #fafafa;
        }

        form {
            max-width: 500px;
            margin: auto;
            margin-top: 50px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"] {
            display: block;
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
            margin-top: 5px;
        }

        input[type="submit"],
        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #008CBA;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            /* margin-top: 15px; */
        }

        input[type="submit"]:hover,
        .btn:hover {
            background-color: #006B9F;
            color: #fff;
        }

        .btn-primary {
            background-color: #ccc;
            color: #000;
        }

        .btn-primary:hover {
            background-color: #aaa;
        }

        p {
            margin: 0;
            margin-top: 30px;
            color: #f57373;
        }
    </style>

</head>

<body>

    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Suggest a new Book 📚</h2>
            <div class="form-group"> {{ form.title }} </div>

            <div class="form-group"> {{ form.author }} </div>

            <div class="form-group"> {{ form.rating }} </div>

            <div class="form-group"> {{ form.price }} </div>

            <div class="form-group"> {{ form.genre }} </div>

            <div class="form-group">{{ form.image }}</div>

            <input class="btn" type="submit" value="Send suggestion" style="margin-top: 15px;">
            <p class="text-center">Don't wanna add a new book? <a href="/" class="btn btn-primary">Cancel</a></p>
        </form>
    </div>
</body>

</html>